FROM quay.io/quarkus/quarkus-distroless-image:2.0
COPY build/libs/code-with-quarkus-1.0.0-SNAPSHOT.jar /application/application.jar

EXPOSE 8080
USER nonroot

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]